export const CHANGE_ACTIVE_TAB = 'CHANGE_ACTIVE_TAB'

export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST'

export const SET_BUSINESS_LIST = 'SET_BUSINESS_LIST'

export const SET_FETCHING_STATE = 'SET_FETCHING_STATE'
